// Generated by Wrangler
// After adding bindings to `wrangler.json`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
    DB: D1Database;
    API_KEY: string;
    JWT_SECRET: string;
}
